config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :locations
  post 'locations/:id/create_part2' => 'locations#create_part2', as: :post_create_part2
  get 'locations/:id/create_part2' => 'locations#create_part2', as: :g_create_part2
  put 'locations/:id/create_part2' => 'locations#create_part2', as: :put_create_part2

  get '/' => 'welcome#home'
  root 'welcome#home'

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_attached_file :empty_still_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :empty_still_image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum account_type: [:producer, :consumer]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :update, :destroy, :create_part2]
  def index
    if current_user.producer?
      @locations = current_user.locations
    else
      @locations = Location.all
    end
  end

  def show
  end

  def new
    @location = Location.new
    @location.user_id = current_user.id
  end

  def create_part2
  end

  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to post_create_part2_path(@location)}
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :number_rows, :number_cols, :queue_list, :empty_still_image, :time_to_clear_queue)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
           
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
   def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end 
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_login_header.html.erb
<div class="main_header">
  <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  <% else %>
    <div id="fake_sign_in_btn"><button>Sign in</button></div>
    <div id="sign_in hide"><%= form_for(:user, :url => session_path(:user)) do |f| %>
      <span class="hiddenText hide"><%= f.text_field :email %></span>
      <span class="hiddenText hide"><%= f.password_field :password %></span>
      <span class="hiddenText hide"><%= f.check_box :remember_me %></span>
      <span class="hiddenText hide"><%= f.label :remember_me %></span>
      <span class="hiddenText hide"><%= f.submit 'Sign in' %></span>
      <span class="hiddenText hide"><%= link_to "Forgot your password?", new_password_path(:user) %></span></div>
    <% end %>
    <div id="register">
      Not a user?
      <%= link_to('Register Now!', new_user_registration_path)  %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Werty</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/login_header" %>
<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location, :url => locations_path, :html => { :multipart => true } do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    Please upload an still shot of your line when it is completely empty:
    <%= form.file_field :empty_still_image %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/create_part2.html.erb
<%= form_for @location do |form| %>
  <div id="empty_image">
    <%= image_tag @location.empty_still_image.url %>
  </div>

  <div class="hidden_num_fields">
    <%= form.hidden_field :number_rows, value: 3 %>
    <%= form.hidden_field :number_cols, value: 4 %>
  </div>
  <div>
    <i class="addRow fa fa-plus-square-o fa-2x">Rows</i>
    <i class="addCol fa fa-plus-square-o fa-2x"> Columns</i>
  </div>
  <div>
    <i class="minusRow fa fa-minus-square-o fa-2x">Rows</i>
    <i class="minusCol fa fa-minus-square-o fa-2x"> Columns</i>
  </div>
  <div>
    <%= form.label :time_to_clear_queue %><br />
    <%= form.text_field :time_to_clear_queue %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/index.html.erb
<div class="container"> 
<table>
  <thead>
    <th>Name</th>
    <th>Avg Time to Clear</th>
  </thead>
  <tbody>
    <% @locations.each_with_index do |location, i| %>
      <tr>
        <td><%= location.name %><%= i %></td>
        <td><%= image_tag location.empty_still_image.url(:thumb) %></td>
        <td><%= link_to 'Show', location %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
Location
<div>
  Name: <%= @location.name %>
</div>

<div>
  Rows: <%= @location.number_rows%><br />
  Cols: <%= @location.number_cols%>
</div>

<div>
  <%= image_tag @location.empty_still_image.url %>
</div>

<div>
  Average Time to clear the queue: <%= @location.time_to_clear_queue%>
</div>
<%= link_to 'Back', locations_path %>

app/views/welcome/_upload_location.html.erb
<%= form_for @location, :url => locations_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :empty_still_image %>
<% end %>

app/views/welcome/home.html.erb
<% if !user_signed_in? %>
  <!--put info about app here --> 
  <div id="home">
        <div id="title">
		<div id="no_q">Because there's no &nbsp;<%= image_tag("q_key.png", :alt => "Q") %> ueue</div>
		<div id="in">in</div>
		<div id="werty_title"><%= image_tag("werty_keys.png", :alt => "WERTY") %></div>                     
        </div>
        <div id="create_btn" class="shownBack"><%= link_to('Create Account', new_user_registration_path)  %></div>
  </div>
  <div class="footer">
        <div> Copyright 2014</div>
  </div>
<% else %>
  <% if current_user.account_type == 'producer' %>
    <!--put upload/monitor info here --> 
    <div>Create Location</div>
    <div>Monitor Location</div>
  <% elsif current_user.account_type == 'consumer' %>
    <!--put search for line here -->
    <div>Search</div> 
  <% else %>
    <div> Don't recognize your account type! </div>
  <% end %>
<% end %>